<?php

use \Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function passwordwidgets_form_alter(&$form, FormStateInterface $form_state, $form_id) {
	$config = \Drupal::service('config.factory')->getEditable('hide_show.settings');
	$form['#attached']['library'][] = 'passwordwidgets/passwordjs';
  $form['#attached']['drupalSettings']['passwordwidgets']['passwordjs']['values'] = $config->get('hide_show_value');
	if($form_id == 'user_register_form' ) {	
		$form['#attached']['drupalSettings']['passwordwidgets']['passwordjs']['password_type'] = $config->get('password_types');;
		$form['#attached']['drupalSettings']['passwordwidgets']['passwordjs']['password_range'] = $config->get('range');
		$form['#attached']['drupalSettings']['passwordwidgets']['passwordjs']['strong_pass'] = $config->get('strong_password');;
	}

  return $form;
}